Add Tasks and Comments entities
kirill-oleynik/ToDoLists_internship pull request #15
Opened 2021-05-05 06:24 UTC by kirill-oleynik

2021-05-11 12:57 UTC, StanisLoveSid requested changes

2021-05-11 12:57 UTC, StanisLoveSid commented on app/concepts/api/v1/comments/operation/create.rb
> +    end
could be moved to Subprocess operation
`payload` from JWT sessions can be used here

2021-05-11 12:57 UTC, StanisLoveSid commented on app/concepts/api/v1/comments/operation/update.rb
> +    end
should be used default validation macroses here

2021-05-11 12:57 UTC, StanisLoveSid commented on config/initializers/shrine.rb
> +    store: Shrine::Storage::FileSystem.new('storage', prefix: 'uploads'),
move to env files

2021-05-11 12:57 UTC, StanisLoveSid commented on config/initializers/shrine.rb
> +Shrine.plugin :determine_mime_type
move to uploader please

2021-05-11 12:57 UTC, StanisLoveSid commented on spec/factories/tasks.rb
> +end
move to trait please

2021-05-11 12:57 UTC, StanisLoveSid commented on spec/models/task_spec.rb
> +end
```ruby
RSpec.describe example, type: :model do
  describe 'model relations' do
    it { is_expected.to belong_to(:example) }

    it { is_expected.to have_one(:example).dependent(:destroy) }
  end
end
```

2021-05-11 12:57 UTC, StanisLoveSid commented on spec/models/user_spec.rb
> +      expect(Task.count).to equal(0)
same as above

2021-05-11 12:57 UTC, StanisLoveSid commented on spec/requests/api/v1/tasks/delete_spec.rb
> +RSpec.describe 'DELETE /v1/tasks/:id', type: :request do
fix all failing request tests please

2021-05-12 10:00 UTC, kirill-oleynik commented on spec/factories/tasks.rb
> +end
Oops! Seems like [FactoryBot gem'sdocumentation](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#has_many-associations) has another opinion. Why do U think that traits is better for this purpose? Lets discuss.

2021-05-12 13:18 UTC, StanisLoveSid approved these changes

2021-05-12 13:18 UTC, StanisLoveSid commented on app/uploaders/application_uploader.rb
> +  Shrine.plugin :determine_mime_type
```suggestion
  plugin :activerecord
  plugin :validation_helpers
  plugin :determine_mime_type
```

2021-05-12 13:18 UTC, StanisLoveSid commented on app/uploaders/image_uploader.rb
> +  Shrine.plugin :restore_cached_data
same as above

2021-05-12 13:18 UTC, StanisLoveSid commented on app/uploaders/application_uploader.rb
> +class ImageUploader < Shrine
naming mistype

2021-05-12 13:18 UTC, StanisLoveSid commented on config/initializers/shrine.rb
> +Shrine.plugin :determine_mime_type
can be moved to upploader

2021-05-12 13:50 UTC, merged